#! /bin/bash

echo === Discard any changes ===
git checkout .

echo === Change to 'dev' branch ===
git checkout dev
git pull origin dev

echo === Build script ===
cd script
rebar3 release

echo === js/projects.js file will be modified if there are any new projects to add. ===
erl -pa _build/default/rel/inaka_github/lib/*/ebin -s inaka_github -noshell -config _build/default/rel/inaka_github/releases/0.1.0/sys.config
cd ..

echo === Copy new project list to parent dir ===
cp web/js/projects.js ../projects.js
git add .
git commit -m "Update projects list."
git push origin dev

echo === Change to 'master' branch ===
git checkout master
git pull origin master

echo === Replace project list ===
mv ../projects.js js/projects.js

echo === Push changes to 'master' ===
git add js/projects.js
git commit -m "Update projects list."
git push origin master

echo === DONE ===
