#! /bin/bash

echo === Discard any changes ===
git co .

echo === Change to 'dev' branch ===
git checkout dev
git pull origin dev

echo === Build script ===
cd script
make

echo === js/projects.js file will be modified if there are any new projects to add. ===
make run
make clean-all
rm -rf log
cd ..

echo === Copy new project list to parent dir ===
cp web/js/projects.js ../projects.js
git add .
git commit -m "Update projects list."
git push origin dev

echo === Change to 'master' branch ===
git checkout master
git pull origin master

echo === Replace project list ===
mv ../projects.js js/projects.js

echo === Push changes to 'master' ===
git add js/projects.js
git commit -m "Update projects list."
git push origin master

echo === DONE ===
