#! /bin/sh
#! /bin/bash
git checkout dev
cd script
make
# Lots of output
make run
# Github user: elvisinaka
# Github password: **********
# The js/projects.js file will be modified if there are any new projects to add.
cd ..
cp web/js/projects.js ../projects.js
git checkout master
cp ../projects.js js/projects.js
git add js/projects.js
git commit -m "Update projects list."
# DONE
